---
title: "OEDA Planning Retreat - Day 1 - Morning"
---

## Intro to Day 1, Morning: Our Foundation

Tuesday, August 5 -- 8:05-2:30

### Brief agenda

- 08:05 -- Roundtable: Imagining Our Future
- 08:30 -- Review & Align: OEDA Activities (yellow sticky notes)
- 09:05 -- Brainstorm & Align: Creating OEDA Units (bounding boxes)
- 10:15 -- 15-minute Break
- 10:30 -- Brainstorm & Align: Identifying Unit Outputs (green sticky notes)
- 11:20 -- Brainstorm & Align: Identifying Unit Audiences (blue sticky notes)
- Noon -- Lunch
- 01:05 -- Brainstorm & Align: Identifying Unit Inputs (orange sticky notes)
- 02:00 -- Align: Rolling Out System 1
- 02:30 -- 15-minute Break

### Day 1, Morning Deliverables

A rough model of OEDA as

- a set of autonomous work units (bounding boxes)
- each engaging in a set of relatively unique activities (yellow sticky notes)
- on inputs received from outside the unit ()
- creating from a set of unique outputs (green sticky notes), and
- delivering to internal and external audiences

Now/next/later prioritization of System 1 units.


## 8:05 -- Activity #1 -- Roundtable: Imagining Our Future

### Purpose

These quick, initial talks will get everyone coming off camera and talking to the team. They will help us begin to think about OEDA activities that our System 1 units will do, and about the kinds of complexities and challenges that Systems 2, 3, 4, and 5 should be designed to help with.

The goal here is not to create an agenda, but to hear from one another about the kind of work that could be possible. I am hoping we start to think about what we and others might need to do to create the kinds of conditions where that work is possible.

### Prompt

*Imagine that OEDA was adequately setup to perform our mandate: integrating and analyzing cross-agency client and customer service data. Describe a kind of project that only OEDA could do in state government. Make it one that you would like to work on, preferably with others on or off of the team.*

-   What are some of the activities that you would contribute?
-   What would you need others to do?
-   What would make the work complex?
-   Who would find value in this work?
-   What could the impact of the work be?

This project does not have to be feasible in OEDA's current state.

### Activity

Each OEDA individual contributor will talk for two or three minutes on a hypothetical future OEDA project.

## 8:30 -- Activity #2 -- Reviewing OEDA Actions

### Purpose

In pre-work activity, you listed the activities that the OEDA team, currently constituted, can or could engage in to bring value to cross-agency stakeholders. We will review and revise this list together.

### Prompt

_What are OEDA's core value-creating activities? What could those be in OEDA's future? What should they be?_

### Background material

### Activity

#### Individual review (10 minutes)

Read others' contributions and add any more you think of (10 minutes)

#### Alignment and refinement (20 minutes)

Ask [clarifying questions](https://www.lucidmeetings.com/glossary/clarifying-question) about any of the cards. Revise cards to fit the constraints

### Constraints

-   Each card should be a [**transitive verb**](https://www.grammarly.com/blog/parts-of-speech/transitive-verbs/) and a [**direct object**](https://www.grammarly.com/blog/parts-of-speech/direct-object/)
    -   The direct object should relate either to
        -   The inputs to the activity (e.g. *analyze data*)
        -   Or to the outputs from the activity (e.g. *create a slide deck*)
- Each card should be **unique**, appearing just once across the entire whiteboard (your section and those of everyone else)
-   Include activities that contribute to **products**; don't include HR training, Workday entry, etc.
-   Activities should **represent the breadth OEDA positions,** based on their general classifications
-   Include activities only for **positions managed by the OEDA manager**; exclude OEDA management, ORRAI leadership, and the data warehouse and reporting positions that OEDA funds

To keep cards unique, you might consider including a modifier/adjective to add specificity to the object. You could freely add one to your card; you might add a note to someone else's card for them to consider a modifier. E.g. rather than a card for "analyze data", you might distinguish between "analyze survey data", "analyze evaluation data", "analyze interview data", or "analyze economic data."

### Deliverable

A list of activities that OEDA staff or teams of staff can perform independently, are within the scope of DAS classifications for RA3, ECON3, and ISS7 positions, and which create value for stakeholders.


## 9:00 -- 5-minute break


## 9:05 -- Activity #3 -- Creating OEDA Units

### Purpose

In this activity, we will explore whether grouping the OEDA actions from Activity #2 might suggest functional units within OEDA. Eventually, these functional units will be more than descriptive. If we identify units, we can create supports and clear expectations and processes for those units: dependencies and sources of inputs, standard operating procedures, checklists and templates, processes for handoffs, and so on.

**This activity is our primary goal for the morning of Day 1.**

### Prompt

*What are OEDA's basic work units?*

### Activity

#### Silent, individual work (20 minutes)

-   Create one or more candidate units as a text box
-   In the text box, provide a high level summary of that unit's basic job
-   Drag and drop cards from Activity #2 into your text box
-   If you see a group someone else has started that you agree with, add a comment or emoji
-   If you see a group that you don't agree with, you can create a different group (duplicating cards, if necessary, and making the duplication visually obvious by connecting duplicated cards)
-   If you develop questions or ideas that don't directly relate to the activity, stick them in a [parking lot](https://www.lucidmeetings.com/glossary/parking-lot)

#### Alignment and refinement (30 minutes)

-   Alignment activity
    -   Modified [gallery walk](https://www.larksuite.com/en_us/topics/meeting-glossary/gallery-method) through the visualized groups, one-by-one
    -   The group creator, or anyone who contributed to the group, will explain the logic behind the grouping
-   Refinement activity; interrogate the groups
    -   Does the group contain every activity it needs to function? What activities are we missing for this group to be truly self-contained?
    -   Would it be reliant on management for *daily* work?
    -   Would it be heavily reliant on another group for *daily* work?
    -   Could a mini-team (even just one person) focused on these activities manage their own workload and work quality?

#### Finalize the groups (10 minutes)

-   Consider the results of refinement
-   [Fist-to-five voting](https://meetingnotes.com/blog/fist-to-five-voting) on whether each is good-enough-for-now
    -   Groups that receive *only* 3, 4, or 5 finger votes will be considered in later sessions during the retreat
    -   Groups that receive *any* 0, 1, or 2 finger votes will not be excluded from later sessions during the retreat

#### Name the groups (10 minutes)

-   Individuals spend a few minutes typing candidate names for any groups
-   [Fist-to-five voting](https://meetingnotes.com/blog/fist-to-five-voting) on whether names are good-enough-for-now
    -   Name suggestions that receive only 3, 4, or 5 finger votes will be adopted; if there are more than on such for a group, we can have a majority vote

### Constraints

-   Units should be **autonomous**.
-   Units should be responsible for a single **product** or class of deliverable. Deliverables can be internal or external.
-   Units should be able to be described with **nouns** labeling the unit, perhaps **proper nouns** naming the unit.
-   Ideally, **use each activity from Step 1 only once**.
-   Our focus this morning will likely be on *standing* units. With what we learn about System 1 units in OEDA, we might in the future also spin up *ad hoc* units for specific projects.

*What does it mean to be autonomous?* When a unit has access to its necessary inputs--which are created outside the unit--they should be able to completely deliver their products using only combinations of the OEDA activities from Step 1. Autonomous units do not need constant direction for their core tasks. They are self-managing: the people in the unit can handle their day-to-day operations and problem-solving. Autonomous units have their own specific environments: a particular dataset, a particular deliverable, a particular set of stakeholders.

*How many units could OEDA have?* There is no preset floor or ceiling on the number of units. Strive to make OEDA's work unit structure as simple as possible, but not simpler.

*What about staffing units?* Do not worry yet about attaching positions or individuals to units. OEDA staff have cross-cutting skills and content expertise, so may end up participating in several functional units, perhaps even on the same project. The same functional unit may have different staff from project to project. This structure is reminiscent of [fission-fusion societies](https://en.wikipedia.org/wiki/Fission%E2%80%93fusion_society). We will address this later.

*What if a function is needed for more than one unit?* If you feel that you need to duplicate a function across more than one unit, first consider:

-   Making the function its own autonomous work unit, delivering products to other units.
-   Duplicating the verb + object pair, but adding modifiers to add specificity and maintain uniqueness.

If these are not ideal, duplicate the function, but show the redundancy visually. Redundancy isn't necessarily bad. It should just be created thoughtfully and transparently.

### Deliverable

A first draft of the standing units in OEDA, each capable of taking inputs, engaging in specific activities to add value to those inputs, and delivering products to others, including other units.


## 10:15 -- 15-minute break


## 10:30 -- Activity #4 -- Identifying Unit Outputs

### Purpose

For the *standing* units which are the focus of this activity, each OEDA unit should create a relatively fixed set of unique and mutually understood outputs. When we are planning future OEDA projects and identify the need for a certain internal deliverable (dataset, analysis, copyedit, accessibility check, etc.) or a external deliverable (application, paper, slide deck, etc.), our team should know the unit or units that will need to be engaged.

### Prompt

*What do OEDA units produce from their activities?*

### Activity

#### Silent, individual work (10 minutes)

-   Add a **green** sticky note to the right hand border of the unit naming one of the outputs from that unit
-   If you see sticky notes from someone else that you agree with, add a comment or emoji
-   If you see a sticky that you don't agree with, you can leave it and create an alternative sticky for that group
-   If you develop questions or ideas that don't directly relate to the activity, stick them in a [parking lot](https://www.lucidmeetings.com/glossary/parking-lot)

#### Alignment and refinement (30 minutes)

-   Alignment activity
    -   Modified [gallery walk](https://www.larksuite.com/en_us/topics/meeting-glossary/gallery-method) through the groups, one-by-one
    -   The creator of the output will share about it, if necessary
-   Refinement activity; interrogate the groups
    -   Does the group contain every activity it needs to function? What activities are we missing for this group to be truly self-contained?
    -   Would it be reliant on management for *daily* work?
    -   Would it be heavily reliant on another group for *daily* work?
    -   Could a mini-team (even just one person) focused on these activities manage their own workload and work quality?

#### Finalize the outputs (10 minutes)

-   Consider the results of refinement
-   [Fist-to-five voting](https://meetingnotes.com/blog/fist-to-five-voting) on whether each is good-enough-for-now
    -   Outputs that receive *only* 3, 4, or 5 finger votes will be adopted as good-enough-for-now output classes for the group and may be considered in later activities during the retreat
    -   Groups that receive *any* 0, 1, or 2 finger votes will be tabled for discussion after the retreat

### Constraints

-   Outputs should be **nouns** or **noun phrases** naming concrete products, not verbs naming activities or processes
-   Every unit should have one or more outputs
-   Outputs should be unique, not repeated across multiple units; consider adding *modifiers* to maintain distinctness
-   Only connect a unit to an output if the unit is primarily **responsible** for the finished output

*Accountable units.* The work of a *COIN unit* may be a precursor to many OEDA research briefs, but that unit might not routinely create research briefs as part of its core work. That team would not be connected to a *research brief* output, even though their work might be vital to those products.

*Using modifiers.* Many units might create research briefs, so we could conceivably identify *research brief* as an OEDA ouput and connect this back to several units: *evaluation unit*, *performance measurement unit*, etc. Alternatively, we could identify *unique* outputs and connect each of these to single units: *evaluation brief*, *measurement brief*, *hypothesis test brief*, etc.

I believe this latter approach will be much more helpful when we work to build OEDA's System 2. System 2 includes supports and procedures for the autonomy and efficiency of System 1 units. When we create checklists, rubrics, templates, boilerplate language, and so on in our System 2, these will be more useful for something specific, like *evaluation brief*, than for a generic *research brief*.

Adding specificity might also help us identify specific outputs that are missing at this point in the retreat, which we may need to assign to a unit, or even create a future unit to handle.

### Deliverable

A menu of OEDA outputs with direct links to the units responsible for those outputs.


## 11:20 -- Activity #5 -- Identifying Unit Audiences

### Purpose

We will identify the **audiences** and **stakeholders** who receive unit outputs. This will help us label each unit. Primary Level 1 units produce their outputs primarily for audiences outside of OEDA: advisory committee members, program and agency leaders, etc. Support units provide their outputs primarily for other OEDA units. This will help us create process maps for OEDA, highlighting

More importantly, taking a few moments to identify the audiences and stakeholders for our slate of OEDA units allows us to take stock of those audiences, and interrogate that array. When we look across the audiences, who is missing? Does missingness suggest outputs missing from our repertoire? Do missing audiences suggest missing work units we need to consider in the future? Identifying these can help set the strategic direction for OEDA's future development.

### Prompt

*Who consumes work from this unit? Whose work depends on the timely completion of this unit's work?*

### Activity

Link each candidate unit, or unit-output pair, to one or more audience. Identify audiences with a *blue* sticky note.

### Constraints

-   Every audience should appear only once
-   Every unit should be connected to at least one audience
-   Every audience should be connected to at least one unit
-   Audiences can be connected to more than one unit
-   If a unit produces more than one output to more than one audience, visually indicate which outputs go to which outputs

Questions for the array of audiences:

-   When we look across our developing audiences, who is missing?
-   Does this suggest outputs that are missing from our repertoire?
-   Does this suggest missing work units we need to consider in the future?


## 12:00 Lunch

## 1:05 -- Activity #6 -- Identifying Unit Inputs

### Purpose

The purpose of this activity is to define the essential prerequisites for each candidate System 1 unit to begin its autonomous work. This serves three primary goals

- To **solidify the boundaries** of each System 1 unit be clearly defining its starting point
- To **create a concrete checklist of inputs that must be in place** before work can be handed off to that unit, increasing transparency and predictability
- To **surface dependencies, bottlenecks, and potential resource conflicts** that will provide the raw material for designing our System 2 (Coordination) functions in a later session


### Prompt

*What are the "starting blocks" for each unit? Think of this as [mise en place](https://en.wikipedia.org/wiki/Mise_en_place) for a recipe--you can't start cooking efficiently until you have all the ingredients measured out on the counter. For each System 1 unit, what are the absolutely essential inputs, permissions, resources, and pieces of information that MUST be in place before that unit can begin its autonomous work?*

Try to be specific about what the unit might need. Broad classes of inputs might include things like *Permissions & Access*, *Data & Information*, or *Scope & Direction*.

### Activity

On a whiteboard populated with our candidate System 1 unit

#### Silent, individual work (10 minutes)

- Add **orange** sticky notes to any unit you like, representing necessary inputs to that unit.
- Generate as many as you can without discussion or judgment.
- If you see sticky notes from others that you agree with, add a comment or emoji.

#### Group discussion and refinement (25 minutes)

- Move through the whiteboard, unit-by-unit, discussing each input
- Clarify: Is this truly a prerequsite, or is it something created or acquired *during* the unit's work? We'll remove anything that isn't a true input.
- Cluster: If sticky notes within a unit are similar, group them and consider a single label. 
- Refine: Edit the language on the stickies to meet constraints and improve clarity.

#### Cross-system patterns (20 minutes)

- Look for patterns across the different units
- Mark with a **star** any input that is required by more than one System 1 unit. These highlight a potential resource conflict or coordination need.
- Mark with a **red flame** any input that the team agrees current has an unknown process, or is difficult, slow, or unreliable to obtain. This highlights known pain points and bottlenecks.

### Constraints

- Each orange sticky note must be a **tangible noun**; it should be a noun or noun phrase, not a verb or process. What is the *thing* that the unit needs to have in hand before it can begin work?
- The input must be a true prerequisite. If acquiring the item is part of the System 1 unit's core work, it is not an input.

### Deliverable

A more detailed process map of OEDA, highlighting some process dependencies. This will include an early list of flagged inputs which might represent shared resources (and thus potential conflicts) or known bottlenecks. These can be an actionable starting point for designing System 2 later in the retreat.

## 2:00 -- Activity #7 -- Rolling Out System 1

### Purpose

Finally, we will conclude our System 1 work by collaboratively sequencing the development and formalization of our System 1 units. This will create a strategic roadmap that clarifies our immediate priorities, manages team workload, and provides a clear, defensible plan to present to our nascent advisory committee. It helps us distinguish between what in OEDA might be operational today versus what is aspirational for the future, near or distant.

### Prompt

_We may not be able to formalize and build the support systems for all of our System 1 units at once. We need to prioritize, considering both importance and readiness. Can we sort our System 1 units into three categories: Now, Next, and Later?_

- **Now:** These units are the most ready to go. We are confident in their basic processes and could support their needs. We feel comfortable presenting these to the OEDA Advisory Committee as a core service today or in the very near future.
- **Next:** These are high-priority units that--because of their outputs, audience, etc.--are crucial to our mission, but which need significant work. This may be securing inputs, refining processes, or dedicating resources. These are what we need to focus OEDA's development efforts on in the near term.
- **Later:** These are units that are either less critical to our immediate strategic goals or require a great deal of work before they can be started. 

### Activity

